services:
  fuxa:
    image: frangoteam/fuxa:latest
    networks:
      - honeynet
    ports:
      - "1881:1881"
    volumes:
      - ./fuxa/fuxa_appdata:/usr/src/app/FUXA/server/_appdata
      - ./fuxa/fuxa_db:/usr/src/app/FUXA/server/_db
      - ./fuxa/fuxa_logs:/usr/src/app/FUXA/server/_logs
    environment:
      - TZ=America/New_York
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - honeynet
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    ports:
      - "11424:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3

    networks:
      - honeynet
#    CMD: ["/bin/sh", "-c", "ollama pull deepseek-coder && ollama serve"]


  honeypot:
    build:
      context: .
      dockerfile: ./honeypot-core/Dockerfile-App
    ports:
      - "2222:2222" # TODO need to change to handle prot 22
      - "502:502"
    depends_on:
      - qdrant
#      - vector_store
      - ollama
    networks:
      - honeynet

networks:
  honeynet:

volumes:
  ollama:
  qdrant_data:
