services:
  fuxa:
    build:
      context: ./honeypot-core/target
      dockerfile: ./Dockerfile-Target
    container_name: ICS
    ports:
      - "1881:1881"
    expose:
      - "2222"
      - "22"
    volumes:
      - ./fuxa/fuxa_appdata:/usr/src/app/FUXA/server/_appdata
      - ./fuxa/fuxa_db:/usr/src/app/FUXA/server/_db
      - ./fuxa/fuxa_logs:/usr/src/app/FUXA/server/_logs
    environment:
      - TZ=America/New_York
    networks:
      - honeynet
      - fuxanet
    depends_on:
      - influxdb
    restart: always
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=ics_logs
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    networks:
      - honeynet
    restart: unless-stopped

  honeypot:
    build:
      context: ./honeypot-core
      dockerfile: Dockerfile-Dev
    environment:
      - DOCKER_API_VERSION=1.49
    volumes:
      - ./honeypot-core:/honeypot-core  # mount entire codebase
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /honeypot-core/app
    ports:
      - "502:502"
      - "1502:1502"
      - "2222:2222"
      - "22:22"
    depends_on:
      - qdrant
      - ollama
    networks:
      honeynet:
        ipv4_address: 192.168.100.9
#      icsnet: {}  # Optional: connect honeypot to ICS network
# ---- Devices ----

  device01:
    container_name: pump01
    build:
      context: ./honeypot-core/app/plc-node
      dockerfile: Dockerfile-Modbus-TCP
    environment:
      "CONTEXT_PATH": "/app/Device-Config/pump_unit_1.json"
    expose:
      - "502"
    volumes:
      - ./honeypot-core/app/plc-node/Device-Config:/app/Device-Config
    networks:
      honeynet:
        ipv4_address: 192.168.100.7

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    expose:
      - "6333"
      - "6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - honeynet
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3
    networks:
      - honeynet
    restart: unless-stopped

volumes:
  ollama:
  qdrant_data:
  fuxa:
  influxdb_data:

networks:
  honeynet:
    name: honeynet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
  fuxanet:
    name: fuxanet
    driver: bridge
    internal: true

#  icsnet:
#    external: true

    #icsnet: {}  # <--- Also here
#  docker network create -d macvlan \
#  --subnet=192.168.100.0/24 \
#  --gateway=192.168.100.1 \
#  -o parent=eth0 \
#  icsnet