services:
  fuxa:
    image: frangoteam/fuxa:latest
    networks:
      - honeynet
      - fuxanet
      # icsnet: {}  # Uncomment to connect FUXA to ICS network
    ports:
      - "1881:1881"
    volumes:
      - ./fuxa/fuxa_appdata:/usr/src/app/FUXA/server/_appdata
      - ./fuxa/fuxa_db:/usr/src/app/FUXA/server/_db
      - ./fuxa/fuxa_logs:/usr/src/app/FUXA/server/_logs
    environment:
      - TZ=America/New_York
    restart: always

  honeypot:
    build:
      context: ./honeypot-core
      dockerfile: Dockerfile-Dev
    environment:
      - DOCKER_API_VERSION=1.49
    volumes:
      - ./honeypot-core:/honeypot-core  # mount entire codebase
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /honeypot-core/app
    ports:
      - "502:502"
      - "1502:1502"
      - "2222:2222"
    depends_on:
      - qdrant
      - ollama
    networks:
      honeynet:
        ipv4_address: 172.18.0.10
#      icsnet: {}  # Optional: connect honeypot to ICS network
# ---- Devices ----

  device01:
    container_name: pump01
    build:
      context: ./honeypot-core/app/plc-node
      dockerfile: Dockerfile-Modbus-TCP
    environment:
      DEVICE_NAME: "PumpUnit1"
      DEVICE_ID: "1"
      DEVICE_MODE: "idle"
      # Temp
      DEVICE_READING_01: "22.5"
      DEVICE_BOUNDS_01: "50"
      # Presure
      DEVICE_READING_02: "68.5"
      DEVICE_BOUNDS_02: "50"
      DEVICE_ERROR: "0"
      DEVICE_IS_RUNNING: "true"
    expose:
      - "502"
    networks:
      honeynet:
        ipv4_address: 172.18.0.15

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    expose:
      - "6333"
      - "6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - honeynet
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3
    networks:
      - honeynet
    restart: unless-stopped

volumes:
  ollama:
  qdrant_data:

networks:
  honeynet:
    name: honeynet
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
  fuxanet:
    name: fuxanet
    driver: bridge

#  icsnet:
#    external: true

    #icsnet: {}  # <--- Also here
#  docker network create -d macvlan \
#  --subnet=192.168.100.0/24 \
#  --gateway=192.168.100.1 \
#  -o parent=eth0 \
#  icsnet