services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - honeynet
    restart: unless-stopped
#  vector_store:
#    image: mongo:latest
#    restart: always
#    ports:
#      - '27017:27017'
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: 'admin'
#      MONGO_INITDB_ROOT_PASSWORD: 'password'
#    volumes:
#      - vector_data:/mongodb/storage
#    networks:
#      - honeynet

  ollama:
    image: ollama/ollama
    ports:
      - "11424:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3

    networks:
      - honeynet
#    CMD: ["/bin/sh", "-c", "ollama pull deepseek-coder && ollama serve"]


  honeypot:
    build:
      context: .
      dockerfile: Dockerfile-App
    ports:
      - "2222:2222" # TODO need to change to handle prot 22
      - "502:502"
    depends_on:
      - qdrant
#      - vector_store
      - ollama
    networks:
      - honeynet

networks:
  honeynet:

volumes:
  ollama:
  qdrant_data:
