
FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum first for dependency caching
COPY go.mod go.sum ./

RUN go mod download

# Copy the rest of the files
COPY . .

# Build the binary
RUN go build -o honeypot ./app/main.go

CMD ["./honeypot"]

