FROM golang:1.24-bookworm AS base

WORKDIR /honeypot

COPY go.mod go.sum ./

COPY /authorized_keys /app/authorized_keys
COPY /ssh_keys   /app/ssh_keys

RUN go mod download

COPY ./  .

RUN go build -o honeypot-core /honeypot/app/main.go

CMD ["/honeypot/honeypot-core"]